spring.application.name=kurs_back
server.port=8080
server.tomcat.uri-encoding=UTF-8

spring.datasource.url=jdbc:postgresql://localhost:5432/sport_kurs
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=mySuperSecretKeyForJWTThatIsAtLeast256BitsLong1234567890
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=2592000000
jwt.issuer=sport-kurs-api

# ===== CORS =====
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

logging.level.com.ssau.kurs_back=DEBUG
logging.level.org.springframework.security=DEBUG





